import api
a = api.Conjunto('A')#É passado como parametro o nome do conjunto
#Função responsavel por inserir elementos no conjunto
a.push('a')
a.push('e')
a.push('i')
a.push('a')#aqui é inserido um elemento que ja existe no conjunto. OBS: elemento não sera repetido
a.push('o')
a.push('u')
print('Tamanho',a.tamanho())
a.imprimir()
print('Pertence:',a.pertence('c'))
B = api.Conjunto('B')
B.push('e')
B.push('i')
B.push('u')
B.imprimir()
print('subconjunto',a.eh_subconjunto(B))
print('Contem propriamente:',a.contem_propriamente(B))
c = api.Conjunto('C')
c.push('a')
c.push('b')
c.push('c')
c.imprimir()
a.uniao(B,c)
a.interseccao(B,c)
